-- AlterTable
ALTER TABLE "staticInfoBond" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "staticInfoCountry" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "staticInfoFund" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "staticInfoFx" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
